### ISSUE TITLE
build error facing 

### ISSUE THREAD

**Issue by amlan007** [BiTGApps/microG-Build#1]
[ 86% 343/396] including vendor/gapps/modules/AppleNLPBackend/Android.mk ...
FAILED:
In file included from build/make/core/shared_library.mk:59:
In file included from vendor/gapps/modules/AppleNLPBackend/Android.mk:26:
In file included from build/make/core/prebuilt.mk:26:
In file included from build/make/core/prebuilt_internal.mk:49:
In file included from build/make/core/app_prebuilt_internal.mk:41:
build/make/core/base_rules.mk:325: error: .: MODULE.TARGET.APPS.AppleNLPBackend already defined by ..

**Comment by TheHitMan7** [comment]
This error log is incomplete, "_**AppleNLPBackend already defined by ..**_" whom ?
